---
tomcat_version: "11.0.25"

tomcat_user: tomcat
tomcat_group: tomcat

tomcat_root: /opt/tomcat
tomcat_install_dir: "{{ tomcat_root }}/apache-tomcat-{{ tomcat_version }}"
tomcat_current_dir: "{{ tomcat_root }}/current"

tomcat_archive_name: "apache-tomcat-{{ tomcat_version }}.tar.gz"

tomcat_archive_url: >-
  https://archive.apache.org/dist/tomcat/tomcat-11/v{{ tomcat_version }}/bin/{{ tomcat_archive_name }}

tomcat_checksum_url: "{{ tomcat_archive_url }}.sha512"

tomcat_port: 8080